### ISSUE TITLE
make all with some error

### ISSUE THREAD

**Issue by cnjack** [rpeshkov/IntelWifi#10]
hardware: Intel Wireless AC 8265
macOS version: 10.13.6 (17G2112)
xcode version: 9.4.1 (9F2000)
build path: /Users/jack/Library/Developer/Xcode/DerivedData/IntelWifi-getlgenyupdyjqbpiohhekunvlkw/Build/Products/Debug/IntelWifi.kext
```
make all

sudo kextunload /Users/jack/Library/Developer/Xcode/DerivedData/IntelWifi-getlgenyupdyjqbpiohhekunvlkw/Build/Products/Debug/IntelWifi.kext
(kernel) Kext net.rpeshkov.IntelWifi not found for unload request.
Failed to unload net.rpeshkov.IntelWifi - (libkern/kext) not found.
```

**Comment by rpeshkov** [comment]
Hi @cnjack, make all command do unload and load. If kext wasn't previously loaded, it fails. I mostly use makefile in this project for easier loading/unloading rather than building pipeline for CI or any kind of build automation.

**Comment by cnjack** [comment]
I build the kext with xcode(sign with ad hoc) then
```
sudo chown -R root:wheel $(KEXT_PATH)
sudo kextutil $(KEXT_PATH)
```
I got `Code Signing Failure: code signature is invalid`

I try
```
sudo nvram boot-args="debug=0x146 kext-dev-mode=1"
```
but it is not work for me

**Comment by cnjack** [comment]
And another question: what different between mvm and dvm, they all implement IOEthernetController, are they some different in hardware?

**Comment by rpeshkov** [comment]
Invalid code signature is fine.

MVM and DVM are operational modes. They're absolutely different in terms of working with the hardware. If you look into iwlwifi module from Linux kernel source you'll see that they mostly don't have any codebase in common.

**Comment by cnjack** [comment]
How can I test the driver?

**Comment by rpeshkov** [comment]
Load kext via kextutil and read logs in Console application. For kext loading you may also use `make load`. This command will change owner of kext to root and load it via kextutil.

**Comment by cnjack** [comment]
Load kext via kextutil return invaild code signture

**Comment by rpeshkov** [comment]
I previously wrote that it's fine. It means that even with invalid signature kext is loaded. You can check loaded kexts with `kextstat` utility. If it's not there, maybe you try this kext on MVM card and kext loading doesn't go further than `probe` call.

**Comment by rpeshkov** [comment]
BTW, if you try to build kext from master branch, there's PCIMatch setup for only Intel Centrino 130 card. You should place identifier for your card inside Info.plist file.

**Comment by cnjack** [comment]
thx
