### ISSUE TITLE
Switch to IO80211Controller

### ISSUE THREAD

**Issue by rpeshkov** [rpeshkov/IntelWifi#5]
Current base class is IOEthernetController that doesn't have a lot of things related to Wifi. Need to switch base class to IO80211Controller.

**Comment by ourfor** [comment]
And how about the status of this driver?

**Comment by rpeshkov** [comment]
All status updates are announced in TonyMacX86 resource. You can start from here https://www.tonymacx86.com/threads/intel-wifi-driver-effort.186344/page-15#post-1722053 to understand the full picture of current state.

**Comment by ourfor** [comment]
@rpeshkov OK，great, It looks like it's going to be successful。

- 
And this problem is Intelwifi.kext?
![2018-07-07 10 32 12](https://user-images.githubusercontent.com/33711476/42411855-29650da8-8236-11e8-8047-356ce365df22.png)

**Comment by rpeshkov** [comment]
@ourfor could you please stop chatting in this issue? If you want to proceed, drop me a message to email or proceed in tonymacx86 forum. 

I will delete all the previous messages in this issue, since they're not related to the issue.

**Comment by jardenliu** [comment]
What type of Wifi card is supported now?
